src/main/java/edu/rpi/legup/Legup.java

Original code get the URL representation of the Legup.jar, which may cause error as space in path would be coded as "%20". By converting URL to URI, the issue is resolved and space is preserved.

fixed space in path error

---

src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/NoNumberContradictionRule.java

**Current Behavior**
Right now there is a bug in the no number contradiction as pointed out in #32. The would incorrectly let you do a contradiction rule.
Additionally, the fill in black rule uses this contradiction rule. The fill in black rule had a bug as pointed out in #30.
**New Behavior**
The bug is no longer present as there is a check to verify all cells around the cell at question are black. This also ended up fixing the other bug.
Closes #32
Closes #30
If you test please try boards that are bugged and boards that work.

Fix "No Number Contradiction"

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

**Current Behavior**
When you check that you have completed a puzzle successfully you are asked if you would like to submit.
**New Behavior**
You are instead given only a message saying your proof is correct.
Closes #36

Remove Submit Message

---

src/main/java/edu/rpi/legup/model/rules/CaseRule.java
src/main/java/edu/rpi/legup/puzzle/lightup/rules/SatisfyNumberCaseRule.java

The number of cases in a case rule must be greater than 1, as otherwise, there wouldn't be multiple cases. Now, the code only enters the if statement if the number of cases is more than 1.
Fixes #45

Issue #45 Fix

---

src/main/java/edu/rpi/legup/model/Puzzle.java
src/main/java/edu/rpi/legup/model/PuzzleExporter.java
src/main/java/edu/rpi/legup/model/PuzzleImporter.java
src/main/java/edu/rpi/legup/model/rules/Rule.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/CantReachWhiteContradictionRule.java

Implemented getRuleByID() and was able to get some basic functionality working (such as being able to change a rule name without breaking the software). Thorough testing needed to verify there are no bugs.

Prototype getRuleByID()

---

src/main/java/edu/rpi/legup/model/gameboard/Board.java

This fixes the issue mentioned below where changing the previous state can prevent you from modifying the board. Only part of the cell was being changed so now the entire cell gets changed.
Fixes #97

Fix Previous State Placement

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

The splash screen used to be artificially delayed by the code to show "Loading..." text. This was removed to load Legup faster for users.

Removed artificial splash screen delay

---

src/main/java/edu/rpi/legup/app/Config.java
src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
src/main/resources/edu/rpi/legup/legup/config

You can now set in the config file whether or not you want the ability to create new files within Legup to be enabled or disabled (primarily to prevent users from accidentally trying to create files for puzzles that are a work in progress)

Added fileCreatonDisabled flag in config file

---

src/main/java/edu/rpi/legup/model/tree/TreeElement.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleShipBoard.java
src/main/java/edu/rpi/legup/puzzle/battleship/rules/AdjacentShipsContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentBoard.java

JavaDoc comments on some board class methods. Also added more methods for identifying other cells in `BattleShipBoard`.

JavaDoc changes and Some Getters For `BattleShipBoard`

---

src/main/java/edu/rpi/legup/app/GameBoardFacade.java
src/main/java/edu/rpi/legup/model/Puzzle.java
src/main/java/edu/rpi/legup/model/PuzzleImporter.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleShip.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleShipImporter.java
src/main/java/edu/rpi/legup/puzzle/fillapix/Fillapix.java
src/main/java/edu/rpi/legup/puzzle/fillapix/FillapixImporter.java
src/main/java/edu/rpi/legup/puzzle/heyawake/Heyawake.java
src/main/java/edu/rpi/legup/puzzle/heyawake/HeyawakeImporter.java
src/main/java/edu/rpi/legup/puzzle/lightup/LightUp.java
src/main/java/edu/rpi/legup/puzzle/lightup/LightUpImporter.java
src/main/java/edu/rpi/legup/puzzle/masyu/Masyu.java
src/main/java/edu/rpi/legup/puzzle/masyu/MasyuImporter.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/Nurikabe.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/NurikabeImporter.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTable.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTableImporter.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/Skyscrapers.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersImporter.java
src/main/java/edu/rpi/legup/puzzle/sudoku/Sudoku.java
src/main/java/edu/rpi/legup/puzzle/sudoku/SudokuImporter.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTent.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentImporter.java
src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

Legup will now show an error message if the number of rows and columns entered is invalid. Note that functionality only works for Sudoku since I didn't implement `isValidDimensions` for any other puzzles (I'll do that later separately).
This implementation is also kind of slow, so I want to increase the speed before we push this to `dev`. I'm just opening a pull request for now because it at least functionally works.

Puzzle Editor Dimension Validation

---

src/main/java/edu/rpi/legup/model/elements/Element.java
src/main/java/edu/rpi/legup/model/rules/Rule.java

Fixed a bug where if you ran the jar file outside of your IntelliJ environment, the element icons would not show up
I ran the jar file outside of my IntelliJ environment and the icons showed up

Fixed visual bug when running jar file outside IntelliJ

---

src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/LegupUI.java

Reverting this pull request because it also makes the user unable to adjust the size of the editor windows.

Revert "PuzzleEditor minimum size temp fix"

---

src/main/java/edu/rpi/legup/app/Config.java
src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
src/main/java/edu/rpi/legup/ui/PickGameDialog.java
src/main/resources/edu/rpi/legup/legup/config

- Spaces are now properly displayed in the puzzle editor selection menu
- Adjusted config file so that only Nurikabe and Tree Tent puzzles can be created

Puzzle editor selection cosmetic changes

---

src/main/java/edu/rpi/legup/app/Config.java
src/main/java/edu/rpi/legup/controller/ElementController.java
src/main/java/edu/rpi/legup/model/gameboard/GridBoard.java
src/main/java/edu/rpi/legup/model/gameboard/PuzzleElement.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/NurikabeCell.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTent.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentBoard.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentCell.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentController.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentExporter.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentImporter.java
src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java

Treetent puzzles can now be edited and saved in the puzzle editor.

Made Treetent Puzzles editable and saveable

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/skyscrapers_reference_sheet.txt

documentation

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersBoard.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersType.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/skyscrapers_reference_sheet.txt

Commented function in skyscrapersBoard. Added to skyscrapers TODO and ref sheet. Added an ANY type to assist helper functions that require a type
Jar compiles

New puzzle skyscrapers

---

src/main/java/edu/rpi/legup/puzzle/lightup/rules/MustLightBasicRule.java

The MustLight rule used the `finalBoard` to determine the rule's use. Now the `parentBoard` is the only board referenced when using the rule.
Closes #119 
NOTE: 
None of the puzzles should allow a final state to determine whether a rule can be used. If any other puzzles were to do that, that rule would have this same self-justification issue (#120).

Fix Must Light Bug (Self Justification)

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/CellForNumberCaseRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/FixedMaxBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/OneEdgeBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/PreemptiveTooManyContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md

Generalized existing rules in terms of case rules
Waiting on dependent rules to test

Fixed Max and OneEdge generalized to use case rules

---

src/main/java/edu/rpi/legup/puzzle/nurikabe/NurikabeUtilities.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/CannotReachCellBasicRule.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/UnreachableWhiteCellContradictionRule.java

Closes #300
Both the `UnreachableWhiteCellContradictionRule` and its corresponding `CannotReachCell` basic rule will now be able to use any black and/or numbered cells to determine that a cell isn't reachable from any region. 
This is a screenshot of this proof file: 
[prtestproof.zip](https://github.com/Bram-Hub/Legup/files/9737907/prtestproof.zip)
If I instead try to choose every square for the rule, I'm shown exactly which ones can and can't be reached.

`UnreachableWhiteCellContradictionRule` Pathfinding

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/LastSingularCellBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/LastSingularNumberBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/LastVisibleCellBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/LastVisibleNumberBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/skyscrapers_reference_sheet.txt

Renamed basic rules

---

src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java

Added skeleton function for drag+drop and extra comments
Co-Authored-By: Weijun Li <83390795+wei-jun7@users.noreply.github.com>
Implements the desired changes from the broken pr chain: https://github.com/Bram-Hub/Legup/pull/389/
- Includes skeleton function for drag and drop feature
- Adds additions comments to flag-checking function in HomePanel
No tests required, other than passing compilation

Skeleton + comments

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/RuleButton.java
src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/RulePanel.java
src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/SearchBarPanel.java

add comments for UI

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/RuleFrame.java
src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/RulePanel.java

When searching for rules in the search panel, the buttons sizes used to not be regulated and the text was on the side making the panel look disorganized. This was because in the searchForRule function, when buttons were created from the found rules there was no changes to the preferred size of the button. I added this code to make the preferred size 150 x 150 and I also moved the text to be at the bottom of the button and centered, like in the other panels. 
In the searchForRule function, when similar rules were found to the search result and a new button was created; I added code to change the preferred size using setPreferredSize, and I changed the positioning of the text using setHorizontalTextPosition and setVerticalTextPosition.
Closes #432 
- [ -] Bug fix (non-breaking change which …

Moved text below icon for search panel

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

Because of how the code is structured, although hitting cancel when opening a file from home worked as intended, hitting cancel after attempting to open an invalid file would cause a null pointer exception. All I had to do was make sure that didn't happen.
This resolves the last of the home panel's file-loading bugs that I know of.
I started Legup, hit `solve puzzle`, attempt to open a random invalid file, then cancel after closing the error message.
This would've caused a null pointer exception before these changes.

Cancel Load Null Pointer

---

src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/CornerBlackDirectRule.java

Closes #447, changed bounds check (likely a typo)
- [ x] Bug fix (non-breaking change which fixes an issue)
Tested on Nurikabe 5x5 Normal 7587733 (original issue) and on Nurikabe Normal 7x7 7958242 bottom left corner. I selected the bottom left corner, clicked until the tile was black, selected "Corners Black" and successfully received the appropriate red triangle error. I went one step back in the tree and selected "Can't Reach Cell" which gave the appropriate success tree.
- [x ] I have performed a self-review of my code
- [x ] My changes generate no new warnings

Fixed Nurikabe Corner Bug

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

From within the proof and puzzle editors, it wasn't possible to open a new puzzle. Now, opening a puzzle from within an editor should have the intended effect of opening a puzzle.
The ActionListener had the wrong function attached to it.
Closes #410
Closes #174 
I opened multiple files from either editor in succession.

Opening Puzzle Bug Fixes

---

bin/main/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTableBoard.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTableImporter.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTableStatement.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md

Short truth table's importer has been bugged seemingly from it's creation, causing some valid proofs to appear invalid after reopening them and causing broken proofs after attempting to alter a reopened proof. The problem was that the statements had to change whenever the cells would change, but one function used in the importer didn't do that. The statements are immutable (since they're PuzzleElements), so any change to a cell requires the whole statement to be rewritten.
My changes keep the statement list updated along with the cells on the board (specificaly for notifyChange).
In the future, the ShortTruthTableStatement class should not be an extension of PuzzleElement<String> and should instead be a sort of look-up-table for cells on the board. For now, rewritting the statements …

Short Truth Table Broken Importer Fixes

---

src/main/java/edu/rpi/legup/puzzle/nurikabe/NurikabeUtilities.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/NoNumberContradictionRule.java

This is a change to the behavior of `NoNumberContradictionRule`, and therefore affects `FillinBlackDirectRule`.
The original code had two problems. First, it tried to check every cell on the board for the rule for each cell (which does n times as many checks as required). Second, when checking for other "possible" white regions, the regions with no white cells were included, bypassing the original check of the cell in question.
Closes #554 
I solved puzzle 1795638 (under 5x5 Normal) by using as much of the contradiction and corresponding direct rule as I could.

No Number Contradiction Bug Fix

---

src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipExporter.java
src/main/java/edu/rpi/legup/puzzle/fillapix/FillapixExporter.java
src/main/java/edu/rpi/legup/puzzle/heyawake/HeyawakeExporter.java
src/main/java/edu/rpi/legup/puzzle/lightup/LightUpExporter.java
src/main/java/edu/rpi/legup/puzzle/masyu/MasyuExporter.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersExporter.java
src/main/java/edu/rpi/legup/puzzle/sudoku/SudokuExporter.java

Fixed a bug where attempting to save a brand new puzzle file created in LEGUP would cause an error since the length of the proof tree would be 0. This fixes that error by adding an if check to get the puzzle board an alternative way if the length of the proof tree is 0.

Null board when creating new puzzle file bug fix

---

src/test/java/puzzles/shorttruthtable/rules/AtomicDirectRuleTest.java
src/test/java/puzzles/shorttruthtable/rules/DirectRuleAtomicTest.java
src/test/resources/puzzles/shorttruthtable/rules/AtomicDirectRule/Empty
src/test/resources/puzzles/shorttruthtable/rules/AtomicDirectRule/FalseA
src/test/resources/puzzles/shorttruthtable/rules/AtomicDirectRule/TrueB

Added tests for Atomic Direct Rule.
Closes #671

Atomic Direct Rule Test

---

src/main/java/edu/rpi/legup/model/gameboard/GridBoard.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentCell.java
src/main/java/edu/rpi/legup/puzzle/treetent/TreeTentCellFactory.java

Uses the code from #530 to fix the treetent puzzle editor.
Where very simple fixes. There was a switch statement missing "break"s. And the TreeTent puzzle exporter was exporting string values, while the importer expected integers.
Closes #503, #530
Created a puzzle using the editor and successfully opened it back up.

Fix treetent puzzle editor

---

.idea/codeStyles/codeStyleConfig.xml
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperCellFactory.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperController.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperElementView.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperImporter.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperTileData.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/rules/LessBombsThanFlagContradictionRule.java

When clicking on tiles, they now cycle from 1-8 for flags, and also cycle between bomb and empty tiles.

Make clicking tiles cycle between numbers, bomb, and empty tiles.

---

src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperBoard.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperTileData.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperUtilities.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/rules/BombOrFilledCaseRule.java
src/test/java/legup/TestRunner.java
src/test/java/puzzles/minesweeper/MinesweeperUtilitiesTest.java
src/test/resources/puzzles/minesweeper/utilities/3x3test

Added some methods to MinesweeperUtilities class to make checking surrounding cells easier. I also added a few unit tests to make sure it worked properly.
I added tests to verify that the correct amount of surrounding cells were found from the function getSurroundingCells.

MinesweeperUtilities Improvements

---

.github/workflows/java-autoformat.yml
src/main/java/edu/rpi/legup/puzzle/lightup/rules/SatisfyNumberCaseRule.java

After seeing the errors thrown by the auto-formatter in #776, I changed the auto-formatter's behavior:
- For pull requests into `dev`, the auto-formatter functions the same, though the method used for detecting formatting changes has been improved.
- For pull requests from `dev`, the auto-formatter will check if there are formatting changes that are necessary. Then, if there are formatting changes, the auto-formatter will open a new pull request with those changes into `dev`. This is because of branch protections, as the auto-formatter doesn't have permissions to directly push onto `dev`.
Note: The changes to `GridRegion.java` were made by the auto-formatter.
I tested these changes in my fork by mimicking the permissions of `master` and `dev`. I then created bad formatting commits both to …

Improved auto-formatter behavior

---

src/main/java/edu/rpi/legup/puzzle/starbattle/rules/EmptyAdjacentDirectRule.java
src/main/java/edu/rpi/legup/puzzle/starbattle/rules/TooFewStarsContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/starbattle/rules/starbattle_reference_sheet.txt
src/test/java/puzzles/starbattle/rules/EmptyAdjacentDirectRuleTest.java
src/test/resources/puzzles/starbattle/rules/EmptyAdjacentDirectRule/ImproperUseFourLeft
src/test/resources/puzzles/starbattle/rules/EmptyAdjacentDirectRule/OneLeft
src/test/resources/puzzles/starbattle/rules/EmptyAdjacentDirectRule/ThreeLeft
src/test/resources/puzzles/starbattle/rules/EmptyAdjacentDirectRule/TwoLeft

Star battle Empty Adjacent Rule (wip)
