Bram-Hub/LEGUP

.gitignore
.idea/misc.xml
.idea/modules/Legup.iml
.idea/modules/Legup_main.iml
.idea/modules/Legup_test.iml
src/main/java/ui/LegupUI.java
src/main/resources/puzzle_gen_script/..\lightup\LightUpBoard2
src/main/resources/puzzle_gen_script/..\lightup\LightUpBoard3
src/main/resources/puzzle_gen_script/makefile
src/main/resources/puzzle_gen_script/puzzle_maker.cpp

Its in the resources folder, if you have Cygwin and g++ just use make, otherwise just build the cpp how you would any other C++ program. 
Will generate puzzle files with proper formatting and naming schemes.

Script for puzzle files

---

src/main/java/edu/rpi/legup/puzzle/lightup/rules/CannotLightACellContradictionRule.java

new update on contradiction rule

---

src/main/java/edu/rpi/legup/ui/lookandfeel/materialdesign/MaterialDrawingUtils.java

Check for null pointer in getAliasedGraphics()

---

src/main/java/edu/rpi/legup/controller/Controller.java
src/main/java/edu/rpi/legup/ui/DynamicView.java

Address issue #9: View Panel zooming bug.
Change the mouse wheel logic to scrolling instead of zooming according to issue #7.

Fix mousewheel scrolling of board and tree panel

---

.gitignore
src/main/java/edu/rpi/legup/puzzle/nurikabe/NurikabeBoard.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/CornerBlackBasicRule.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/NoNumberContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/TooFewSpacesContradictionRule.java
src/main/java/edu/rpi/legup/utility/ConnectedRegions.java

Fix Issue 31: Corners Black Out Bug

---

src/main/java/edu/rpi/legup/model/rules/CaseRule.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/BlackOrWhiteCaseRule.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/caserule/CaseRuleAtomic.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/caserule/CaseRule_Generic.java

Short truth table case rules can no longer be used to justify any changes.
Fixes #54

Issue #54 Fix

---

src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/basic/BasicRule_Generic.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/caserule/CaseRuleAtomic.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/caserule/CaseRule_Generic.java

Adjusted logic in CaseRule_Generic.java so an if statement didn't check the for the same possibility twice.
Solves #73

Truth table issue73 case rule bug

---

src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/basic/BasicRule_Generic.java

Adjusted verification process for Truth Table elimination rules to improve accuracy
Closes #76

Fixed Issue #76

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

Batch grader fixes complete in LegupUI.java . Outputs to csv file were adapted to requests and a recursive directory traversal method was made. Paths are now shown in output by name entry. For the future, flags should be added to legup files to determine proof completion instead of simulating each board. 
Closes #50

Batch grader

---

README.md
contributing.md

Created contributing.md and made slight modifications to README.md.
Closes #112

Created contributing.md file and slight modifications to README

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

Don't have access to mac so WIP and will need to be tested

[WIP] #106 changed redo from ctrl+y to ctrl+shift+z

---

src/main/java/edu/rpi/legup/ui/LegupUI.java
src/main/java/edu/rpi/legup/ui/boardview/BoardView.java

UI issue108 change puzzleview text in the puzzle panel to puzzle board

---

src/main/java/edu/rpi/legup/controller/Controller.java

Two-finger scroll bug

---

src/main/java/edu/rpi/legup/controller/Controller.java
src/main/java/edu/rpi/legup/ui/DynamicView.java
src/main/java/edu/rpi/legup/ui/LegupUI.java
src/main/java/edu/rpi/legup/ui/ScrollView.java

Some exception handling, null assertions, and other spaghetti code fixes.

Minor Fixes

---

src/main/java/edu/rpi/legup/controller/Controller.java
src/main/java/edu/rpi/legup/controller/TreeController.java
src/main/java/edu/rpi/legup/ui/ScrollView.java

The tree view panel scroll is changed back to normal. The mouse wheel scroll now works up and down as desired.

[Fixed] UI issue128 remove tree view pinch to zoom

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

Fix screen resize issue

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

Added a column to display puzzle type

Adjustments made to Batch Grader

---

README.md
bin/main/edu/rpi/legup/legup/config
src/main/java/edu/rpi/legup/puzzle/battleship/Battleship.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipBoard.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipCell.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipCellController.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipCellFactory.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipClue.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipClueView.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipElementView.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipExporter.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipImporter.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipType.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipView.java
src/main/resources/edu/rpi/legup/legup/config

Refactored classes to fix camel-casing.

Refactored Battleship classes

---

src/main/java/edu/rpi/legup/puzzle/battleship/BattleShipBoard.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipBoard.java
src/main/java/edu/rpi/legup/puzzle/battleship/rules/AdjacentShipsContradictionRule.java

Removed JetBrains annotations.

---

src/main/java/edu/rpi/legup/ui/LegupUI.java

Update LegupUI issue 152

---

src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipCellController.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipElementView.java
src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipType.java
src/main/java/edu/rpi/legup/puzzle/battleship/rules/AdjacentShipsContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/battleship/rules/ContinueShipBasicRule.java
src/main/java/edu/rpi/legup/puzzle/treetent/rules/TouchingTentsContradictionRule.java

Changed `BattleshipType` enums to be shorter, and revised some JavaDoc comments for better clarity and easier readability.

Battleship Enums Changed and Revised JavaDoc Comments

---

src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/LegupUI.java
src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

Added an exit option to the puzzle editor and proof editor menus to allow users to return to the home screen.

Puzzle editor exit button

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/ExceedingVisibilityContradictionRule.java

minor edits to exceeding visibility contradiction rule

New puzzle skyscrapers

---

src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipBoard.java
src/main/java/edu/rpi/legup/puzzle/battleship/rules/AdjacentShipsContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/rules/IsolateBlackContradictionRule.java
src/test/java/puzzles/battleship/rules/AdjacentShipsContradictionRuleTest.java

- Implementation
- Incomplete test
Also some JavaDoc revisions.

Battleship: Adjacent Ships Contradiction Rule

---

src/main/java/edu/rpi/legup/app/GameBoardFacade.java
src/main/java/edu/rpi/legup/controller/CursorController.java
src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

- Created a method that can be called in GameBoardFacade that can be called to check if some given dimensions are valid for a particular puzzle
- Created the CursorController class to have the cursor change to a loading cursor since validating the dimensions and creating the new puzzle file takes time
- Note: this class can be used for other applications as well

Improvements to dimension validator

---

src/main/java/edu/rpi/legup/puzzle/lightup/elements/BlackTile.java
src/main/java/edu/rpi/legup/puzzle/lightup/elements/BulbTile.java
src/main/java/edu/rpi/legup/puzzle/lightup/elements/NumberTile.java

Added placeable and non-placeable elements to the lightup puzzle file.

Added elements to lightup puzzle

---

src/main/java/edu/rpi/legup/puzzle/lightup/elements/BulbTile.java
src/main/java/edu/rpi/legup/puzzle/lightup/elements/NumberTile.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/elements/NumberTile.java

Fixed semantic errors/Added nurikabe placeable/non-placeable objects

---

.idea/misc.xml
src/main/java/edu/rpi/legup/ui/DynamicView.java
src/main/java/edu/rpi/legup/ui/LegupUI.java

UI issue 100

---

src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
src/main/java/edu/rpi/legup/ui/HomePanel.java

Redoing overwritten UI changes.

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java

Fixed directory preference issue

---

src/main/java/edu/rpi/legup/app/GameBoardFacade.java
src/main/java/edu/rpi/legup/controller/EditorElementController.java
src/main/java/edu/rpi/legup/controller/ElementController.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

fixed nullpointerexception in proof editor

---

src/main/java/edu/rpi/legup/puzzle/nurikabe/elements/NumberTile.java
src/main/java/edu/rpi/legup/puzzle/sudoku/elements/NumberTile.java

Added place-able object to Sudoku puzzle type. Fixed documentation on previous Non-place-able objects for the Nurikabe puzzle-type.
Successful compile and execute w/ no new warnings or errors.
-> Place-able object now in Sudoku puzzle.

Puzzle editor

---

src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java

Implemented "Contribute to Legup" option and changed link from someone's fork to the main repository.
I clicked on the buttons that I implemented functionality for and they seem to work as intended.

Contribute to Legup link changed

---

src/main/java/edu/rpi/legup/ui/HomePanel.java

Opens preferences on start menu

Fixed Issue 240

---

src/main/java/edu/rpi/legup/ui/puzzleeditorui/elementsview/ElementFrame.java

non-placeable elements go first

Puzzle editor: changed order of editor element tabs

---

src/test/java/puzzles/battleship/rules/FinishWithShipsBasicRuleTests.java
src/test/resources/puzzles/battleship/rules/FinishWithShipsBasicRule/HorizontalValidBoard

Added implementation for Battleship basic rule "Finish With Ships".
Some unit tests and test puzzle files tailored explicitly for the rule.

Battleship: Finish With Ships Basic Rule

---

src/main/java/edu/rpi/legup/model/PuzzleExporter.java
src/main/java/edu/rpi/legup/puzzle/nurikabe/NurikabeExporter.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

Saving Nurikabe Puzzles is now active

---

src/main/java/edu/rpi/legup/puzzle/treetent/TreeTent.java
src/main/java/edu/rpi/legup/puzzle/treetent/elements/GrassTile.java
src/main/java/edu/rpi/legup/puzzle/treetent/elements/TentTile.java
src/main/java/edu/rpi/legup/puzzle/treetent/elements/TreeTile.java

Puzzle editor: started adding element classes for treetent

---

src/main/java/edu/rpi/legup/controller/EditorElementController.java
src/main/java/edu/rpi/legup/ui/puzzleeditorui/elementsview/ElementButton.java

Now, the puzzle editor tool will display a green border when selected.
Closes #294(issue)

Tool Select Indicator for Puzzle Editor

---

CONTRIBUTING.md

Merging commit "Restore CONTRIBUTING.md" from master to dev.

"Restore CONTRIBUTING.md" from master => dev

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java

It is an unfinished version. With talking to the group leader, we decide to use a web page to replace the Pop-up window dialog. So far, the web page hasn't set up yet, I just put Github legup link here, waiting to have a real dialog web page in the future.
- [yes] New feature (non-breaking change which adds functionality)
- [yes] I have commented my code, particularly in hard-to-understand areas

Halfway - Menu Improvements + Providing Help to User

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/PreemptiveVisibilityContradictionRule.java

Preemptive Visibility Contradiction rule completed and tested 
- [# ] New feature (non-breaking change which adds functionality)
simple testing by running test cases through LegUp 
- [# ] I have commented my code, particularly in hard-to-understand areas
- [# ] I have made corresponding changes to the documentation (if applicable)
- [#] My changes generate no new warnings

PreemptiveVisibilityContradictionRule completed + tested

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/CellForNumberCaseRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/NumberForCellCaseRule.java

Added Icons
launch a puzzle and look at the icons

Case rules now use preemptive visibility

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java

Char song24 re UI saving proof file issue

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersClueView.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersView.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/CellForNumberCaseRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/TODO.md

added highlighting for row/col clue selection

---

src/main/java/edu/rpi/legup/ui/puzzleeditorui/elementsview/ElementFrame.java

UI problem 309 is fixed now

---

src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/RulePanel.java

For example, there is a rule "Empty Corners". Before, users can only find this rule by typing exactly the same name. Now, if you input "E", "Emp", and so on, "Empty Corners" can also be found, and others rules that there is a "Empty" in their name can also be found.
Closes #388 
- [y ] I have performed a self-review of my code
- [y ] I have commented my code, particularly in hard-to-understand areas

Similarity check searching algorithm for search bar

---

src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersBoard.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/SkyscrapersImporter.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/CellForNumberCaseRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/LastVisibleCellBasicRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/NumberForCellCaseRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/PreemptiveVisibilityContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/skyscrapers/rules/UnresolvedCellContradictionRule.java

Attempt to fix checkstyle errs

---

.github/workflows/publish-javadoc.yml

Branch for testing automated Javadoc deployment and hosting on GH Pages

Javadoc hosting

---

src/main/java/edu/rpi/legup/ui/HomePanel.java
src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

From the home panel, after clicking the `Solve Puzzle` button, canceling would open an empty proof editor.
The issue isn't listed.

Cancel `Solve Puzzle`

---

puzzles files/shorttruthtable/Heuveln_01.xml

N/A since this is only an idea for a new file format

Adjusted file to reflect potential idea for file rework

---

src/main/java/edu/rpi/legup/ui/proofeditorui/rulesview/RulePanel.java

Pressing ENTER with the rule search text box selected is the same as pressing the Go button next to the text box.
Closes #434

Pressing ENTER is the same as pressing Go putton in rule search

---

src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/AndTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/BiconditionalTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/ConditionalTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/GreenTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/LetterTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/NegationTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/OrTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/ParenthesisTile.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/RedTile.java

This is the start of some work of implementing the puzzle editor for Short Truth Table. I have only created the element files in this pull request. No new functionality was implemented.

Created files for STT elements

---

src/main/java/edu/rpi/legup/puzzle/shorttruthtable/rules/contradiction/ContradictionRuleBiconditional.java

Someone copy pasted wrong from the reference sheet, simply replaced with correct string. Closes #419

File importer bug

---

src/main/java/edu/rpi/legup/app/LegupPreferences.java
src/main/java/edu/rpi/legup/ui/LegupUI.java
src/main/java/edu/rpi/legup/ui/PreferencesDialog.java

Added a checkbox under general preferences in the preferences menu that toggles night mode on/off. Toggles between FlatLightLaf and FlatDarkLaf. 
Closes #404 (https://github.com/Bram-Hub/LEGUP/issues/404)
- [x ] New feature (non-breaking change which adds functionality)

[ENHANCEMENT] Add dark mode #404

---

src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

Revert "Update PuzzleEditorPanel.java"

---

src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

Revert of commit 847af1b129d0c244148315beca7427e8f432a35c
onClearHistory caused a null pointer exception that broke the proof editor.

Revert onClearHistory Commit

---

src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java

The help button on the puzzle editor and puzzle solver take you to the correct spots in the wiki.

Help button

---

src/main/java/edu/rpi/legup/puzzle/battleship/BattleshipType.java
src/main/java/edu/rpi/legup/ui/WrapLayout.java

Javadocs process on `dev` still has some problems. I removed the remaining problematic HTML tags in this pull request.
Can't really be tested until we run the GitHub Action.

Removed more HTML tags

---

src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTableCell.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/AndOrElement.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/ArgumentElement.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/ConditionalBiconditionalElement.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/LogicSymbolElement.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/UnknownElement.java
src/main/java/edu/rpi/legup/puzzle/shorttruthtable/elements/shorttruthtable_elements_reference_sheet

Combined and/or and conditional/biconditional elements

Only one logic symbol element needed

---

src/test/java/legup/TestRunner.java
src/test/java/legup/TestUtilities.java
src/test/java/puzzles/battleship/rules/TestRunner.java

Original Behavior: 
The tests from the puzzles weren't just run in one file.
New Behavior: 
closes #476. 
Runs the tests from src/test/java/puzzles in one file, src/test/java/legup/TestUtilities.java.
closes #476.

Get Tests to be called

---

src/main/java/edu/rpi/legup/puzzle/shorttruthtable/ShortTruthTableExporter.java

Fixed the bug where you couldn't save files of puzzles you newly created.

Saving files now works

---

settings.gradle

Modified the root project name in `settings.gradle` to the new all-caps root directory.
By reloading indicies after adjusting the name and checking any Java files to have the appropriate syntax highlighting. Building and running the application also works fine.

Adjusted Gradle Settings to Reflect Updated Project Name

---

src/test/java/puzzles/shorttruthtable/rules/BiconditionalIntroductionTest.java
src/test/java/puzzles/shorttruthtable/rules/ConditionalIntroductionTest.java
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/FUF
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/FUT
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/FUU
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/TUF
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/TUT
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/TUU
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/UUF
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/UUT
src/test/resources/puzzles/shorttruthtable/rules/BiconditionalIntroductionDirectRule/UUU
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/FUF
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/FUT
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/FUU
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/TUF
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/TUT
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/TUU
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/UUF
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/UUT
src/test/resources/puzzles/shorttruthtable/rules/ConditionalIntroductionDirectRule/UUU

Added conditional introduction and biconditional introduction tests.
Closes #667, #668

Added Conditional Introduction and Biconditional Introduction tests

---

settings.gradle
src/test/java/puzzles/lightup/rules/EmptyCornersDirectRuleTest.java
src/test/resources/puzzles/lightup/rules/EmptyCornersDirectRule/EmptyCorners

I tested the rule by editing the existing puzzle file to include more space for more tests. I also edited the test code accordingly while leaving comments to explain what I did. I tested if the rule didn't work if used incorrectly which it didn't, meaning that it was correct and the it worked. 
Closes #(573)
I made extra tests to check if the rule was correct.

EmptyCornerDirectRuleTest Finished

---

src/main/java/edu/rpi/legup/puzzle/minesweeper/Minesweeper.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperBoard.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperCell.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperCellFactory.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperController.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperElementIdentifiers.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperElementView.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperExporter.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperImporter.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperTileData.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperTileType.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperView.java
src/main/resources/edu/rpi/legup/legup/config

Beginning implementation of Minesweeper, mostly using the Nurikabe code.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes

Initial Minesweeper implementation work

---

src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperController.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperElementIdentifiers.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperExporter.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperImporter.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperTileData.java
src/main/java/edu/rpi/legup/puzzle/minesweeper/MinesweeperTileType.java

Add Unset tile type
- [ X] New feature (non-breaking change which adds functionality)
- [ X] I have performed a self-review of my code
- [ X] My changes generate no new warnings
- [ X] New and existing unit tests pass locally with my changes

Add Unset tile type

---

src/main/java/edu/rpi/legup/puzzle/binary/BinaryType.java

BinaryType file complete. Will be used to represent the different possible grid cell values.
Based off the NurikabeType code.

Implementing the BinaryType file for the grid cell possibilities

---

src/main/java/edu/rpi/legup/puzzle/binary/Binary.java
src/main/java/edu/rpi/legup/puzzle/binary/BinaryBoard.java
src/main/java/edu/rpi/legup/puzzle/binary/BinaryCell.java
src/main/java/edu/rpi/legup/puzzle/binary/BinaryExporter.java
src/main/java/edu/rpi/legup/puzzle/binary/BinaryImporter.java
src/main/java/edu/rpi/legup/puzzle/binary/elements/BlankTile.java
src/main/java/edu/rpi/legup/puzzle/binary/elements/NumberTile.java

Began adding some necessary class files for implementing the new binary puzzle
Modified existing puzzle importer class from nurikabe with added error checking for binary puzzle board parameters

Initialized files, wrote puzzle importer

---

src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerController.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerFill.java
src/main/java/edu/rpi/legup/puzzle/thermometer/rules/MercuryOrBlockedCaseRule.java

Added the first case rule Mercury or Blocked. Not commented, just wanted to get a working rule in to make the GUI setup a bit easier. Also changed ThermometerController to better reflect how we wanted the user to interact with the puzzle.
Hasn't yet, no test cases yet.

Thermometer first rule and changes to ThermometerController

---

src/main/java/edu/rpi/legup/puzzle/sudoku/PossibleNumberCaseBoard.java
src/main/java/edu/rpi/legup/puzzle/sudoku/rules/NoCellForNumberContradictionRule.java
src/main/java/edu/rpi/legup/puzzle/sudoku/rules/PossibleCellsForNumberCaseRule.java
src/main/java/edu/rpi/legup/puzzle/sudoku/rules/PossibleNumbersForCellCaseRule.java

Refactored Case Rules to match wiki description and fixed bug that only checked regions and not all group types.
Went into any sudoku puzzle and used Possible Numbers for Cell rule to check if the numbers/branches that appeared created any contradictions or left any possible numbers out. Checked this for multiple spots to verify its functionality.

Refactoring and bug fixes

---

src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerBoard.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerController.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerElementView.java
src/main/java/edu/rpi/legup/puzzle/thermometer/elements/Vial.java

Added the Vial class which will be important for verifying rules. Also made some small format cleanups. 
No tests have been done yet as we will need to write rules to figure out whether this is useful.

Thermometer

---

src/main/resources/edu/rpi/legup/legup/config

Updated the proper config file to support Binary in LEGUP.
I am now able to open the sample Binary file in the puzzle files directory.

Update config file to include Binary

---

src/main/java/edu/rpi/legup/puzzle/binary/rules/SurroundPairDirectRule.java
src/main/java/edu/rpi/legup/puzzle/binary/rules/ThreeAdjacentContradictionRule.java

fixed buggy contradiction rule

Fixed buggy three adjacent contradiction rule

---

src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerBoard.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerController.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerExporter.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerImporter.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerNumberView.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerView.java

Working row/column numbers are here! Now the user can fully interact with the board and we are able to successfully store/access all information that would be needed for writing rules.
Manual testing, I ensured that no previously working functionality was broken by the introduction of these cells.

Working row/col numbers

---

src/main/java/edu/rpi/legup/puzzle/thermometer/Thermometer.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerBoard.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerCell.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerController.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerElementView.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerImporter.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerVial.java
src/main/java/edu/rpi/legup/puzzle/thermometer/ThermometerView.java

Some comments explaining our code to try and help anyone who wishes to work on this project in the future.

Last minute comments

---

src/main/java/edu/rpi/legup/puzzle/starbattle/rules/TooFewStarsContradictionRule.java
src/test/java/puzzles/starbattle/rules/ClashingOrbitContradictionRuleTest.java
src/test/java/puzzles/starbattle/rules/SurroundStarDirectRuleTest.java
src/test/java/puzzles/starbattle/rules/TooFewStarsContradictionRuleTest.java
src/test/resources/puzzles/starbattle/rules/SurroundStarDirectRule/CenterStar
src/test/resources/puzzles/starbattle/rules/SurroundStarDirectRule/CornerStar
src/test/resources/puzzles/starbattle/rules/TooFewStarsContradictionRule/Column
src/test/resources/puzzles/starbattle/rules/TooFewStarsContradictionRule/FalseContradiction
src/test/resources/puzzles/starbattle/rules/TooFewStarsContradictionRule/Region
src/test/resources/puzzles/starbattle/rules/TooFewStarsContradictionRule/Row

Star battle

---

.settings/org.eclipse.buildship.core.prefs
src/main/java/edu/rpi/legup/puzzle/binary/BinaryBoard.java
src/main/java/edu/rpi/legup/puzzle/binary/rules/EliminateTheImpossibleDirectRule.java

added functions to eliminate the impossible (still wip)

---

src/main/java/edu/rpi/legup/puzzle/binary/rules/EliminateTheImpossibleDirectRule.java

Added row functionality for eliminate the impossible

---

src/main/java/edu/rpi/legup/puzzle/starbattle/StarBattleBorderView.java

Some extra work to make borders black and fill in the empty corners

Black Borders with corners

---

src/main/java/edu/rpi/legup/puzzle/starbattle/StarBattleBorderView.java
src/main/java/edu/rpi/legup/puzzle/starbattle/StarBattleView.java

Back to black coloring and properly centered plus outside board borders properly aligned.

Better border definition

---

src/main/java/edu/rpi/legup/puzzle/starbattle/StarBattleBorder.java
src/main/java/edu/rpi/legup/puzzle/starbattle/StarBattleView.java

Prep for text tiles

---

src/main/java/edu/rpi/legup/puzzle/starbattle/StarBattleView.java

Add future function comment
